### ISSUE TITLE
Gestion des sauvegardes

### ISSUE THREAD

**Issue by vinki11** [vinki11/superawesomerpg#11]
- Permettre de sauvegarder une partie
- Permettre de charger une partie

De la manière que je vois ça tout ce qu'on a besoin de gardé en save c'est ce qui concerne :  
- Le groupe d'aventurier (liste des membres, inventaires, piecès d'ors
- Les aventuriers (leurs caractéristiques et leur équipement actif)

**Comment by Balour** [comment]
Closed par commit #33
